# Common configuration.

AllCops:
  Exclude:
    - bin/bundle

Norb/ActiveRecordThroughBusiness:
  Description: 'Direct ActiveRecord calls should come from business objects.'
  Enabled: true
  Include:
    - app/models/**/*.rb

Norb/MisplacedBranchingLogic:
  Description: 'Branching logic in these locations should be moved to business objects.'
  Enabled: true
  BranchMethods:
    - if
    - and
    - or
    - case
    - resbody
  Include:
    - app/models/ar/**/*.rb
    - app/controllers/**/*.rb
    - app/views/**/*.erb


Norb/ActiveRecordNamespaced:
  Description: 'ActiveRecord models should be namespaced.'
  Enabled: true
  ActiveRecordNamespace: Ar
  ActiveRecordSuperclasses:
    - ActiveRecord
    - ApplicationRecord
  Include:
    - app/models/**/*.rb
