# Common configuration.

AllCops:
  Exclude:
    - bin/bundle

Norb/ActiveRecordThroughBusiness:
  Description: 'Direct ActiveRecord calls should come from business objects.'
  Enabled: true
  Exclude:
    - app/models/**/*.rb

Norb/BranchingLogic:
  Description: 'Branching logic in these locations should be moved to business objects.'
  Enabled: true
  BranchMethods:
    - if
    - and
    - or
    - case
    - resbody
  Exclude:
    - lib/**/*.rb
    - !ruby/regexp /app\/models\/(?!db\/).*\.rb$/

Norb/ActiveRecordNamespaced:
  Description: 'ActiveRecord models should be namespaced.'
  Enabled: true
  ActiveRecordNamespace: DB
  ActiveRecordSuperclasses:
    - ActiveRecord
    - ApplicationRecord
  Include:
    - app/models/**/*.rb

Norb/MisplacedLogic:
  Description: 'Code should primarily be placed in models and lib.'
  Enabled: true
  Include:
    - app/**/*.rb
  Exclude:
    - app/{models,controllers,views}/**/*.rb

Norb/OneControllerActionInstanceVariable:
  Description: 'Rails Controller actions should only instantiate one instance variable.'
  Enabled: true
  Include:
    - app/controllers/**/*_controller.rb

Norb/StandardRestfulControllerActions:
  Description: 'Ensure Rails Controllers only use standard RESTful actions'
  Enabled: true
  Include:
    - app/controllers/**/*_controller.rb
