# Common configuration.

AllCops:
  Exclude:
    - bin/bundle
  # What version of Rails is the inspected code using?  If a value is specified
  # for TargetRailsVersion then it is used.  Acceptable values are specificed
  # as a float (i.e. 5.1); the patch version of Rails should not be included.
  # If TargetRailsVersion is not set, RuboCop will parse the Gemfile.lock or
  # gems.locked file to find the version of Rails that has been bound to the
  # application.  If neither of those files exist, RuboCop will use Rails 5.0
  # as the default.
  TargetRailsVersion: ~

Norb/MisplacedBranchingLogic:
  Description: 'Branching logic in these locations should be moved to business classes.'
  Enabled: true
  VersionAdded: '0.75'
  BranchMethods:
    - if
    - and
    - or
    - case
    - resbody
  Include:
    - app/models/ar/**/*.rb
    - app/controllers/**/*.rb
    - app/views/**/*.erb


Norb/NamespacedActiveRecord:
  Description: 'ActiveRecord models should be namespaced.'
  Enabled: true
  VersionAdded: '0.76'
  ActiveRecordNamespace: Ar
  ActiveRecordSuperclasses:
    - ActiveRecord
    - ApplicationRecord
  Include:
    - app/models/**/*.rb
