# Common configuration.

AllCops:
  Exclude:
    - bin/bundle

Norb/ActiveRecordThroughBusiness:
  Description: 'Direct ActiveRecord calls should come from business objects.'
  Enabled: true
  Exclude:
    - app/models/**/*.rb

Norb/BranchingLogic:
  Description: 'Branching logic in these locations should be moved to business objects.'
  Enabled: true
  BranchMethods:
    - if
    - case
    - resbody
  Include:
    - app/models/db/**/*.rb

Norb/BinaryOperation:
  Description: 'This cop checks for binary logic in non-business code.'
  Enabled: true
  Exclude:
    - !ruby/regexp /app\/models\/(?!db\/).*\.rb$/
    - config/environments/**/*.rb
    - lib/**/*.{rb,rake}
    - spec/**/*.rb
    - test/**/*.rb

Norb/ActiveRecordNamespaced:
  Description: 'ActiveRecord models should be namespaced.'
  Enabled: true
  ActiveRecordNamespace: DB
  ActiveRecordSuperclasses:
    - ActiveRecord
    - ApplicationRecord
  Include:
    - app/models/**/*.rb

Norb/OneControllerActionInstanceVariable:
  Description: 'Rails Controller actions should only instantiate one instance variable.'
  Enabled: true
  Include:
    - app/controllers/**/*_controller.rb

Norb/StandardRestfulControllerActions:
  Description: 'Ensure Rails Controllers only use standard RESTful actions'
  Enabled: true
  Include:
    - app/controllers/**/*_controller.rb


Norb/RailsAppTypeNotAllowed:
  Description: 'These Rails classes/types are not approved.'
  Enabled: true
  Include:
    - app/helpers/**/*.rb
    - app/services/**/*.rb
    - app/decorators/**/*.rb
    - app/policies/**/*.rb
    - app/support/**/*.rb
